version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: lymbus_user
      POSTGRES_PASSWORD: lymbus_password
      POSTGRES_DB: lymbus
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./app
    command: npm start
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend

volumes:
  postgres_data:
