name: CI

on:
  pull_request:
    branches: ["*"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: lymbus_user
          POSTGRES_PASSWORD: lymbus_password
          POSTGRES_DB: lymbus
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt
      - name: Run backend scripts (optional tests)
        run: |
          echo "No tests defined"
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build frontend
        run: |
          cd app
          npm ci
          npm run build --if-present
